### ISSUE TITLE
Add another method (like init) to run after the transform

### ISSUE THREAD

**Issue by bencoveney** [tusharmath/ts-codemod#3]
Hi - thanks for the great tool 😄 

I would like to add a check to be run after a file has been processed. I'm not sure this is possible at the moment - but I could potentially do it if there was a method on the `Transform` class that was called after the transform is done, like `postTransform()` or `after()` or `close` or something.

The reason for wanting this:

We have some info about our TypeScript code in another file - e.g. a list of parameters for a constructor. I would like to check after the transform that all the info (e.g. parameter info) from the file has been used in-case:
- My transform is wrong and missed a parameter or
- The info in the file was wrong or
- Something else unexpected happened.

I think this would be a good addition since I expect it is common to use the transform to process large numbers of files, so it would be good to be able to add some safety checks.

Let me know what you think. I would be happy to make the change if you think this is a good addition.

**Comment by tusharmath** [comment]
Hi @bencoveney 

The purpose of this module is to provide you basic tooling to write custom code mods for typescript based code. 

If I got what you are saying — Then the errors you are talking about should be caught either by typescript or tslint automatically. 


To fix those lint errors, you could add multiple transformation and run them consecutively.

**Comment by bencoveney** [comment]
Hi @tusharmath

I will try and give a bit of a better explaination - that might make it easier to discuss:

We have hundreds of microservices that use dependency injection. For each microservice there is a
.ts file and a .json file.

```JavaScript
export default class TheClassToModify implements Dependency3 {
	constructor(arg1: Interface1) { }
}
```

```JSON
{
	"dependencies": [
		{
			"name": "Interface1",
			"metadata": "Data1"
		},
		{
			"name": "Interface2",
			"metadata": "Data2"
		}
	],
	"exports": [
		"Interface3"
	]
}
```

We are removing the `.json` files, and trying to end up with the following TypeScript instead:

```TypeScript
export default class TheClassToModify implements Exports<Dependency3> {
	constructor(arg1: Dependency<Interface1, "Data1">) { }
}
```

But you can see above, there was some information in the `.json` file that did not get used in the
transform (`Data2`). I would like to check for this, and warn the user or fail the transform if the
data in `.json` file does not match what the transform finds in the file.

My transform looks like this at the moment (pseudocode):

```
class MyTransform extends Transform {
	init() {
		// Load .json file.
	}
	visit(node) {
		if (ts.isHeritageClause(node) && jsonFileContainsExport(node)) {
			// Add Export<...>
		}
		if (ts.isParameter(node) && jsonFileContainsDependency(node)) {
			// Add Dependency<...>
		}
	}
	after() {
		// Check everything from the JSON file was used.
	}
}
```

Without an `after()` step I don't know how I could check that everything from the `.json` file was
used? ts-lint and typescript would not error on my code, because the code is
syntactically/semantically correct - It just doesn't match the `.json` file.

You are correct that maybe I could add a tslint rule to check that the `.json` and `.ts` file have
matching content but for me that will be slower than adding the `after()` method on a fork, and it
will be harder for other developers to run on their in-progress git branches if they have to use
multiple tools.

Anyway thanks for getting back to me quickly :smile: Feel free to close if you do not want this feature.

**Comment by tusharmath** [comment]
@bencoveney help me understand one more thing, given the following input — 
```ts
export default class TheClassToModify implements Dependency3 {
  constructor(arg1: Interface1) {}
}
```
What is the expected output ?

### Option 1

```ts
export default class TheClassToModify implements Exports<Dependency3> {
  constructor(arg1: Dependency<Interface1, 'Data1'>) {}
}
```

### Option 2

```ts
export default class TheClassToModify implements Exports<Dependency3> {
  constructor(
    arg1: Dependency<Interface1, 'Data1'>,
    arg2: Dependency<Interface2, 'Data2'>
  ) {}
}
```

In either case you can write a code mod that can read the `.json` file and apply the appropriate transformation.

**Comment by tusharmath** [comment]
But if you just want a warning and not perform any transformation then you would probably need an `after` method. It could probably work it like `init()`.

**Comment by bencoveney** [comment]
Yep thats it, Option 1 + `WARNING: JSON expected 2 parameters but ClassToModify only had one`
