### ISSUE TITLE
The file is changed in a strange way

### ISSUE THREAD

**Issue by brugnara** [tusharmath/ts-codemod#8]
Not sure why but this tool removes lines between methods and also removes spaces randomly.

This is the output I've got:

![image](https://user-images.githubusercontent.com/2781191/147296237-8a6e7793-2e0b-4dd1-9d73-b067f0dfb896.png)

with this config file:

    {
      transformation: 'shift-imports',
      params: {
        // name of the source module
        from: '@foo/bar',

        // name of the target module
        to: '@foo/bar/MapDataKind',

        // all the import specifiers that should be migrated
        imports: ['MapDataKind', 'Map']
      }
    }

Am I missing something? 🤔 
Thank you for considering my request and thank you for this promising tool.

**Comment by brugnara** [comment]
That's well written in the doc, sorry, I only spotted now :) 

https://github.com/tusharmath/ts-codemod#post-transformation

**Comment by tusharmath** [comment]
Great!
